version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: intranet_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: intranet
      MYSQL_USER: myuser
      MYSQL_PASSWORD: toor
    volumes:
      - ./config/my.cnf:/etc/mysql/my.cnf
      - db_data:/var/lib/mysql

networks:
  default:
    name: intranet_default
volumes:
  db_data:
